Update for Joomla 4

diff --git a/src/jbackup b/src/jbackup
--- a/src/jbackup
+++ b/src/jbackup
@@ -1,26 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 
 # jbackup -- Create a full backup (including database) of a Joomla website to .tgz file.
-# Supports Joomla 1.0 - 3.3
+# Supports Joomla versions 2.5 - 4.x
 #
-# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
+# Copyright 2014 -2021 Rene Kreijveld - email@renekreijveld.nl
 #
 # This program is free software; you may redistribute it and/or modify it.
 #
 # Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
 #
 # Version history
-# 3.0 Initial version
-# 3.1 Added usage
-# 3.2 Code rewrite and remove -e option in echos
-# 3.3 Typo correction
+# 1.0 Initial version
+# 1.1 Added usage
+# 1.2 Code rewrite and remove -e option in echos
+# 1.3 Typo correction
+# 1.4 Added test if jfunctions exists
 
 # Determine path of script
 mypath=$(cd $(dirname ${0}); pwd -P)
 myname=$(basename ${0})
 
 # Version
-version=3.3
+version=1.4
 
 # display usage information
 usage() {
@@ -38,10 +39,9 @@ usage() {
 	exit 0
 }
 
-# Default no zipfile
-zip="no"
 
 # process the arguments
+zip="no"
 while getopts zth opt; do
 	case "${opt}" in
 		z) zip="yes";;
@@ -51,16 +51,25 @@ while getopts zth opt; do
 done
 
 # include general functions
-. ${mypath}/jfunctions
+if [ ! -e ${mypath}/jfunctions ]
+then
+	echo ""
+	echo "Cannot continue: script jfunctions not found."
+	echo ""
+	exit 1
+else
+	. ${mypath}/jfunctions
+fi
 
 echo ""
 echo "${myname} version ${version}, written by Rene Kreijveld."
 echo ""
-echo "This is a Joomla! ${versr}.${versd} site. Starting backup..."
+echo "This is a Joomla! ${jversion} site. Starting backup..."
 
 # dump the database to a .sql file
 echo "Creating database dump..."
-if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} --socket=${mysock} ${database} > ${database}.sql; then
+if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} ${database} > ${database}.sql
+then
 	echo "${database}.sql created."
 else
 	echo "Error creating database dump."
@@ -68,14 +77,16 @@ else
 fi
 
 # check if htaccess is present
-if [ -e .htaccess ]; then
+if [ -e .htaccess ]
+then
 	htaccess=".htaccess"
 else
 	htaccess=""
 fi
 
 # create the backup
-if [ "${zip}" == "no" ]; then
+if [ "${zip}" == "no" ]
+then
 	tar czf ${sitename}.tgz ${htaccess} *
 	echo "Your backup is ready in ${sitename}.tgz:"
 	ls -l ${sitename}.tgz
@@ -85,5 +96,5 @@ else
 	ls -l ${sitename}.zip
 fi
 
-# cleanup datebase dump
+# cleanup the datebase dump
 rm ${database}.sql
diff --git a/src/jdbdump b/src/jdbdump
--- a/src/jdbdump
+++ b/src/jdbdump
@@ -1,39 +1,102 @@
-#!/bin/sh
+#!/bin/bash
 
 # jdbdump -- Dump a Joomla database to sql file.
 #
-# This scripts supports Joomla versions 1.0 - 3.3
+# This scripts supports Joomla versions 2.5 - 4.x
 #
-# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
-#
+# Copyright 2014 - 2022 Rene Kreijveld - email@renekreijveld.nl
 # This program is free software; you may redistribute it and/or modify it.
 #
 # Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
 #
 # Version history
-# 3.0 Initial version
-# 3.1 Code rewrite
-# 3.2 Modification of all echo -e statements
+# 1.0 Initial version
+# 1.1 Code rewrite
+# 1.2 Modification of all echo -e statements
+# 1.3 Added test if jfunctions exists
+# 1.4 Added compress option
 
 # general variables
 mypath=$(cd $(dirname ${0}); pwd -P)
 myname=$(basename ${0})
 
 # include general functions
-. ${mypath}/jfunctions
+if [ ! -e ${mypath}/jfunctions ]
+then
+	echo ""
+	echo "Cannot continue: script jfunctions not found."
+	echo ""
+	exit 1
+else
+	# gather joomla information
+	. ${mypath}/jfunctions
+fi
 
 # version
-version=3.2
+version=1.4
+
+# display usage information
+usage() {
+	echo ""
+	echo "${myname} version ${version}, written by Rene Kreijveld."
+	echo ""
+	echo "Usage: ${myname} [-d] [-c] [-h]"
+	echo ""
+	echo "-d Add a date-time-stamp to the database dump filename."
+	echo "-c Compress the database dump with gzip."
+	echo "-h Help. Display this info."
+	echo ""
+	exit 0
+}
+
+# process the arguments
+compress="no"
+while getopts dch opt; do
+	case "${opt}" in
+		d)
+			showdate="yes"
+			;;
+		c)
+			compress="yes"
+			;;
+		h)
+			usage
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+		:)
+			echo "Option -$OPTARG requires an argument." >&2
+			exit 1
+			;;
+	esac
+done
+
+if [ "${showdate}" == "yes" ]
+then
+	now=$(date +".%Y%m%d-%H%M%S")
+else
+	now=""
+fi
 
 echo ""
 echo "${myname} version ${version}, written by Rene Kreijveld."
 echo ""
-echo "This is a Joomla! ${versr}.${versd} site. Starting database dump..."
+echo "This is a Joomla! ${jversion} site. Starting database dump..."
 
 # dump the database to a .sql file
-if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} --socket=${mysock} ${database} > ${database}.sql; then
-	echo "${database}.sql created."
-	ls -l ${database}.sql
+if mysqldump --skip-opt --extended-insert=FALSE --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} ${database} > ${database}${now}.sql
+then
+	if [ "${compress}" == "yes" ]
+	then
+		gzip ${database}${now}.sql
+		echo "${database}${now}.sql.gz created (compressed with gzip)."
+		ls -l ${database}${now}.sql.gz
+	else
+		echo "${database}${now}.sql created."
+		ls -l ${database}${now}.sql
+	fi
 	exit 0
 else
 	echo "Error creating database dump."
diff --git a/src/jdbimp b/src/jdbimp
--- a/src/jdbimp
+++ b/src/jdbimp
@@ -1,42 +1,54 @@
 #!/bin/sh
 
 # jdbimp -- Import a sql file into a Joomla database.
-# Supports Joomla versions 1.0 - 3.3
+# Supports Joomla versions 2.5 - 4.x
 #
-# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
-#
+# Copyright 2014 - 2021 Rene Kreijveld - email@renekreijveld.nl
 # This program is free software; you may redistribute it and/or modify it.
 #
 # Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
 #
 # Version history
-# 3.0 Initial version
-# 3.1 Code rewrite
-# 3.2 Modification of all echo -e statements
+# 1.0 Initial version
+# 1.1 Code rewrite
+# 1.2 Modification of all echo -e statements
+# 1.3 Added test if jfunctions exists
 
 # general variables
 mypath=$(cd $(dirname ${0}); pwd -P)
 myname=$(basename ${0})
 
 # include general functions
-. ${mypath}/jfunctions
+if [ ! -e ${mypath}/jfunctions ]
+then
+	echo ""
+	echo "Cannot continue: script jfunctions not found."
+	echo ""
+	exit 1
+else
+	# gather joomla information
+	. ${mypath}/jfunctions
+fi
 
 # version
-version=3.2
+version=1.3
 
 echo ""
 echo "${myname} version ${version}, written by Rene Kreijveld."
 echo ""
-echo "This is a Joomla! ${versr}.${versd} site. Starting database import..."
+echo "This is a Joomla! ${jversion} site. Starting database import of ${database}.sql."
 
 # check if database dump exists.
-if [ ! -e ${database}.sql ]; then
-	echo "Database dump ${database}.sql not found!"
+if [ ! -e ${database}.sql ]
+then
+	echo "Database dump file not found. The filemname should be ${database}.sql."
+	echo ""
 	exit 1
 fi
 
 # import the database from a .sql file
-if mysql --host=${host} --user=${dbuser} --password=${password} --socket=${mysock} ${database} < ${database}.sql; then
+if mysql --host=${host} --user=${dbuser} --password=${password} ${database} < ${database}.sql
+then
 	echo "${database}.sql imported."
 	exit 0
 else
diff --git a/src/jlistjoomlas b/src/jlistjoomlas
--- a/src/jlistjoomlas
+++ b/src/jlistjoomlas
@@ -1,23 +1,24 @@
-#!/bin/sh
+#!/bin/bash
 
-# jlistjoomlas -- Find Joomla instances on your (DirectAdmin based) server.
-# Supports Joomla versions 1.0 - 3.4
+# jlistjoomlas -- Find Joomla instances on your Linux server.
+# Supports Joomla versions 1.0 - 4.x
 #
-# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
-#
+# Copyright 2014 - 2022 Rene Kreijveld - email@renekreijveld.nl
 # This program is free software; you may redistribute it and/or modify it.
 #
 # Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
 #
 # Version history
-# 3.0 Initial version
-# 3.1 Code rewrite
-# 3.2 Added CSV option
-# 3.3 Modification of all echo -e statements
-# 3.4 Added release version option
+# 1.0 Initial version
+# 1.1 Code rewrite
+# 1.2 Added CSV option
+# 1.3 Modification of all echo -e statements
+# 1.4 Added release version option
+# 1.5 Added test if jfunctions exists
+# 1.6 Start folder set to /home, this is default for a Runcloud server
 
 # define variables
-version=3.4
+version=1.6
 mypath=$(cd $(dirname ${0}); pwd -P)
 myname=$(basename ${0})
 startdir=/home
@@ -63,57 +64,73 @@ do
 	esac
 done
 
-if [ "${csv}" == "no" ]; then
-	if [ "${short}" == "no" ]; then
+if [ "${csv}" == "no" ]
+then
+	if [ "${short}" == "no" ]
+	then
 		echo ""
 		echo "${myname} version ${version}, written by Rene Kreijveld."
 		echo ""
 	fi
 fi
 
-if [ "${csv}" == "yes" ]; then
+if [ "${csv}" == "yes" ]
+then
 	echo "\"map\",\"name\",\"version\",\"database\",\"dbuser\",\"password\",\"host\",\"prefix\""
 fi
 
-for dir in $(find ${startdir} -maxdepth 4 -type d -name "public_html")
+for dir in $(find ${startdir} -maxdepth 4 -type d)
 do
-	if [ -f ${dir}/configuration.php ]; then
+	if [ -f ${dir}/configuration.php ]
+	then
 		# possible joomla found
 		cd ${dir}
-		if [ "${csv}" == "no" ]; then
-			if [ "${short}" == "no" ]; then
+		if [ "${csv}" == "no" ]
+		then
+			if [ "${short}" == "no" ]
+			then
 				echo Possible Joomla found in ${dir}
 			fi
 		fi
 
 		# get Joomla information
-		. ${mypath}/jfunctions
-
-		if [ ! -z "${releaseversion}" ] && [ "${releaseversion}" != "${versr}" ]; then
-			if [ "${csv}" == "no" ] && [ "${short}" == "no" ]; then
-				echo Skipping ${versr} is not ${releaseversion}
+		if [ ! -e ${mypath}/jfunctions ]
+		then
+			echo ""
+			echo "Cannot continue: script jfunctions not found."
+			echo ""
+			exit 1
+		else
+			. ${mypath}/jfunctions
+		fi
+		if [ ! -z "${releaseversion}" ] && [ "${releaseversion}" != "${jversion}" ]
+		then
+			if [ "${csv}" == "no" ] && [ "${short}" == "no" ]
+			then
+				echo Skipping, found version is ${jversion} and not ${releaseversion}.
 			fi
 			continue;
 		fi
 
 		# output information
-		if [ "${csv}" == "yes" ]; then
-			echo "\"${dir}\",\"${sitename}\",\"${versr}.${versd} ${verss}\",\"${database}\",\"${dbuser}\",\"${password}\",\"${host}\",\"${prefix}\",\"${logpath}\""
+		if [ "${csv}" == "yes" ]
+		then
+			echo "\"${dir}\",\"${sitename}\",\"${jversion}\",\"${database}\",\"${dbuser}\",\"${password}\",\"${host}\",\"${prefix}\""
 		else
-			if [ "${short}" == "no" ]; then
+			if [ "${short}" == "no" ]
+			then
 				echo "Joomla information found:"
 				echo "Sitename    : ${sitename}"
-				echo "Version     : ${versr}.${versd} ${verss}"
+				echo "Version     : ${jversion}"
 				echo "DB Name     : ${database}"
 				echo "DB User     : ${dbuser}"
 				echo "DB Password : ${password}"
 				echo "DB Host     : ${host}"
 				echo "DB Prefix   : ${prefix}"
-				echo "Log path    : ${logpath}"
 				echo ""
 			else
 				echo "Joomla found in ${dir}"
-				echo "Version: ${versr}.${versd} ${verss}"
+				echo "Version: ${jversion}"
 				echo ""
 			fi
 		fi
diff --git a/src/joomlainfo b/src/joomlainfo
--- a/src/joomlainfo
+++ b/src/joomlainfo
@@ -1,28 +1,36 @@
-#!/bin/sh
+#!/bin/bash
 
-# jinfo -- Provide information about this Joomla! installation.
-# Supports Joomla 1.0 - 3.3
+# joomlainfo -- Provide information about this Joomla! installation.
+# Supports Joomla 1.0 - 4.x
 #
-# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
-#
+# Copyright 2014 - 2022 Rene Kreijveld - email@renekreijveld.nl
 # This program is free software; you may redistribute it and/or modify it.
 #
 # Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
 #
 # Version history
-# 3.0 Initial version
-# 3.1 Code rewrite
-# 3.2 Modification of all echo -e statements
+# 1.0 Initial version
+# 1.1 Code rewrite
+# 1.2 Modification of all echo -e statements
+# 1.3 Added test if jfunctions exists
 
 # general variables
 mypath=$(cd $(dirname ${0}); pwd -P)
 myname=$(basename ${0})
 
 # include general functions
-. ${mypath}/jfunctions
+if [ ! -e ${mypath}/jfunctions ]
+then
+	echo ""
+	echo "Cannot continue: script jfunctions not found."
+	echo ""
+	exit 1
+else
+	. ${mypath}/jfunctions
+fi
 
 # version
-version=3.2
+version=1.3
 
 echo ""
 echo "${myname} verion ${version}, written by Rene Kreijveld."
@@ -31,12 +39,11 @@ echo ""
 # output information
 echo "This Joomla! website:"
 echo "Sitename    :" $sitenameclean
-echo "Version     :" $versr.$versd $verss
+echo "Version     :" $jversion
 echo "DB Name     :" $database
 echo "DB User     :" $dbuser
 echo "DB Password :" $password
 echo "DB Host     :" $host
 echo "DB Prefix   :" $prefix
 echo "Path        :" `pwd`
-echo "Log path    :" $logpath
 echo ""
